"""Strict payload contracts and JSON serialization."""

from ._contracts import (
    ContentTypeMismatchError,
    FormatMismatchError,
    ForyConcurrencyError,
    ForyRegistrationError,
    InvalidMetadataError,
    MalformedPayloadError,
    PayloadLimitError,
    PayloadMetadata,
    SchemaMismatchError,
    SerdeEncodeError,
    SerdeError,
    SerdeErrorCode,
    SerializedPayload,
    TrustProfile,
    TrustProfileMismatchError,
    TypeMismatchError,
    UnsupportedVersionError,
)
from ._json import (
    DEFAULT_MAX_INPUT_SIZE,
    DEFAULT_MAX_NESTING_DEPTH,
    DEFAULT_MAX_OUTPUT_SIZE,
    MAX_JSON_INTEGER_DIGITS,
    MAX_SUPPORTED_NESTING_DEPTH,
    JsonValue,
    json_deserialize,
    json_serialize,
)

__all__ = [  # noqa: RUF022 - staged public contract order is intentional
    "DEFAULT_MAX_INPUT_SIZE",
    "DEFAULT_MAX_OUTPUT_SIZE",
    "DEFAULT_MAX_NESTING_DEPTH",
    "MAX_SUPPORTED_NESTING_DEPTH",
    "MAX_JSON_INTEGER_DIGITS",
    "ContentTypeMismatchError",
    "ForyConcurrencyError",
    "ForyRegistrationError",
    "FormatMismatchError",
    "InvalidMetadataError",
    "JsonValue",
    "MalformedPayloadError",
    "PayloadLimitError",
    "PayloadMetadata",
    "SchemaMismatchError",
    "SerializedPayload",
    "SerdeError",
    "SerdeErrorCode",
    "SerdeEncodeError",
    "TrustProfile",
    "TrustProfileMismatchError",
    "TypeMismatchError",
    "UnsupportedVersionError",
    "json_deserialize",
    "json_serialize",
]
